#include "xblcom.h"

#include "xbl.h"

const int NCOM = 73;

const std::vector<std::string> COM1_NAMES = {
    "",
    "X1",
    "U1",
    "T1",
    "D1",
    "S1",
    "AMPL1",
    "U1_UEI",
    "U1_MS",
    "DW1",
    "H1",
    "H1_T1",
    "H1_D1",
    "M1",
    "M1_U1",
    "M1_MS",
    "R1",
    "R1_U1",
    "R1_MS",
    "V1",
    "V1_U1",
    "V1_MS",
    "V1_RE",
    "HK1",
    "HK1_U1",
    "HK1_T1",
    "HK1_D1",
    "HK1_MS",
    "HS1",
    "HS1_U1",
    "HS1_T1",
    "HS1_D1",
    "HS1_MS",
    "HS1_RE",
    "HC1",
    "HC1_U1",
    "HC1_T1",
    "HC1_D1",
    "HC1_MS",
    "RT1",
    "RT1_U1",
    "RT1_T1",
    "RT1_MS",
    "RT1_RE",
    "CF1",
    "CF1_U1",
    "CF1_T1",
    "CF1_D1",
    "CF1_MS",
    "CF1_RE",
    "DI1",
    "DI1_U1",
    "DI1_T1",
    "DI1_D1",
    "DI1_S1",
    "DI1_MS",
    "DI1_RE",
    "US1",
    "US1_U1",
    "US1_T1",
    "US1_D1",
    "US1_MS",
    "US1_RE",
    "CQ1",
    "CQ1_U1",
    "CQ1_T1",
    "CQ1_D1",
    "CQ1_MS",
    "CQ1_RE",
    "DE1",
    "DE1_U1",
    "DE1_T1",
    "DE1_D1",
    "DE1_MS",
};

const std::vector<std::string> COM2_NAMES = {
    "",
    "X2",
    "U2",
    "T2",
    "D2",
    "S2",
    "AMPL2",
    "U2_UEI",
    "U2_MS",
    "DW2",
    "H2",
    "H2_T2",
    "H2_D2",
    "M2",
    "M2_U2",
    "M2_MS",
    "R2",
    "R2_U2",
    "R2_MS",
    "V2",
    "V2_U2",
    "V2_MS",
    "V2_RE",
    "HK2",
    "HK2_U2",
    "HK2_T2",
    "HK2_D2",
    "HK2_MS",
    "HS2",
    "HS2_U2",
    "HS2_T2",
    "HS2_D2",
    "HS2_MS",
    "HS2_RE",
    "HC2",
    "HC2_U2",
    "HC2_T2",
    "HC2_D2",
    "HC2_MS",
    "RT2",
    "RT2_U2",
    "RT2_T2",
    "RT2_MS",
    "RT2_RE",
    "CF2",
    "CF2_U2",
    "CF2_T2",
    "CF2_D2",
    "CF2_MS",
    "CF2_RE",
    "DI2",
    "DI2_U2",
    "DI2_T2",
    "DI2_D2",
    "DI2_S2",
    "DI2_MS",
    "DI2_RE",
    "US2",
    "US2_U2",
    "US2_T2",
    "US2_D2",
    "US2_MS",
    "US2_RE",
    "CQ2",
    "CQ2_U2",
    "CQ2_T2",
    "CQ2_D2",
    "CQ2_MS",
    "CQ2_RE",
    "DE2",
    "DE2_U2",
    "DE2_T2",
    "DE2_D2",
    "DE2_MS",
};

void sync_com_to_vars(XBlState &bl, int which) {
    const std::vector<double> &src = (which == 1) ? bl.COM1 : bl.COM2;
    const std::vector<double *> &dst = (which == 1) ? bl.com1_fields : bl.com2_fields;
    for (int i = 1; i <= NCOM; ++i) {
        if (dst[i]) {
            *dst[i] = src[i];
        }
    }
}

void sync_vars_to_com(XBlState &bl, int which) {
    std::vector<double> &dst = (which == 1) ? bl.COM1 : bl.COM2;
    const std::vector<double *> &src = (which == 1) ? bl.com1_fields : bl.com2_fields;
    for (int i = 1; i <= NCOM; ++i) {
        if (src[i]) {
            dst[i] = *src[i];
        } else {
            dst[i] = 0.0;
        }
    }
}
